#!/bin/sh

FILE="test.cpp"

SUFFIX="(f|l|F|L|f16|f32|f64|f128|bf16|F16|F32|F64|F128|BF16)"
DIGIT_SEQUENCE="[0-9]+"
EXPONENT_SIGN="[+-]?"
DECIMAL_EXPONENT="[eE]$EXPONENT_SIGN$DIGIT_SEQUENCE"

HEX_DIGIT_SEQUENCE="[0-9a-fA-F]+"
HEX_EXPONENT="[pP]$EXPONENT_SIGN$DIGIT_SEQUENCE"

REGEXP_FIRST="$DIGIT_SEQUENCE$DECIMAL_EXPONENT$SUFFIX?"
REGEXP_SECOND="$DIGIT_SEQUENCE\.($DECIMAL_EXPONENT)?$SUFFIX?"
REGEXP_THIRD="($DIGIT_SEQUENCE)?\.$DIGIT_SEQUENCE($DECIMAL_EXPONENT)?$SUFFIX?"

HEX_PREFIX="(0x|0X)"
REGEXP_HEX_FIRST_SECOND="$HEX_PREFIX$HEX_DIGIT_SEQUENCE\.?$HEX_EXPONENT$SUFFIX?"
REGEXP_HEX_THIRD="$HEX_PREFIX($HEX_DIGIT_SEQUENCE)\.$HEX_DIGIT_SEQUENCE$HEX_EXPONENT$SUFFIX?"

REGEXP="($REGEXP_FIRST|$REGEXP_SECOND|$REGEXP_THIRD|$REGEXP_HEX_FIRST_SECOND|$REGEXP_HEX_THIRD)"
grep -n -o -E "$REGEXP" $FILE